# Configuration file for training model.

# data path
task_name: immunology 

# training

num_bio_labels:  3

corpus_dir: data/Mesh/PubMed/Immunology/finetune/conll

# restore model
restore_model: True
restore_model_path: experiments/immunology/segmentation/models/model_best_seg.pth

# model save dir
model_dir: experiments/immunology/segmentation/models/finetune


# bert model
seed: 22
#model_checkpoint: allenai/scibert_scivocab_cased
model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768
hidden_size: 100

# label num
# span label
class_num: 2

# gpu
gpu: 0

# training
train_epochs: 50
train_batch_size: 32
valid_batch_size: 32

# training lr
train_lr: 1e-4
train_scheduler: linear
train_num_warmup_steps: 100
max_patient_count: 5



