# Configuration file for training model.

# data path
task_name: immunology 


dict_dir: data/UMLS/dict
processed_dict_dir: data/UMLS/processed_dict

document_root_dir: data/Mesh/PubMed/Immunology/extract
es_dump_path: data/Mesh/PubMed/Immunology/database/dump/abstract_dump.json


entity_names:
        - Cytokine 
        - Transcription_Factor
        - T_Lymphocyte

# model save dir
model_dir: experiments/immunology/models/finetune


# bert model
seed: 22
#model_checkpoint: allenai/scibert_scivocab_cased
model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768

# positive label num
positive_class_num: 3

# gpu
gpu: 0 

# training
train_epochs: 50
train_batch_size:  32 
valid_batch_size: 32 
test_batch_size: 8 


# training lr
train_lr: 1e-4
train_scheduler: linear
train_num_warmup_steps: 100 
max_patient_count: 20 


# restore model
restore_model: True
restore_model_path: experiments/immunology/models/model_best_final.pth

