# Configuration file for training model.

# data path
task_name: bc5cdr 
cnt: 5
iteration: 5

text_dir: data/BC5CDR/eval/text

ann_dir: 
    - data/BC5CDR/eval/annotate.It_W6_S0.5_R1_5_5
#   - data/BC5CDR/eval/annotate.It_W6_S0.5_R1
#    - data/BC5CDR/eval/annotate.autoner
#    - data/BC5CDR/eval/annotate.supervised
#    - data/BC5CDR/eval/annotate.debug
#    - data/BC5CDR/eval/annotate.roster
#    - data/BC5CDR/eval/annotate.bond2
