# Configuration file for training model.

# data path
task_name: bc5cdr 


#gold_sample_ratio: 0.01
#random_seed: 1

gold_sample_ratio: 0.5 
random_seed: 1 

updated_documents: data/BC5CDR/finetune/updated_doc.json
unchanged_documents: data/BC5CDR/finetune/unchanged_doc.json

gold_annotation_dir: data/BC5CDR/gold
annotation_dir: data/BC5CDR/annotate
text_dir: data/BC5CDR/corpus

#conll_dir: data/BC5CDR/finetune/conll
#span_dir: data/BC5CDR/finetune/span
simulation_dir: data/BC5CDR/finetune/S0.5_R1
conll_dir: data/BC5CDR/finetune/S0.5_R1/conll
span_dir: data/BC5CDR/finetune/S0.5_R1/span

entity_names:
        - Chemical 
        - Disease
    
