# Configuration file for training model.

# data path
task_name: bc5cdr 


finetune_dir: data/BC5CDR/finetune/Scratch_W6_S1.0_R1
corpus_dir: data/BC5CDR/finetune/Scratch_W6_S1.0_R1/span


# model save dir
model_root_dir: experiments/bc5cdr/models
model_dir: experiments/bc5cdr/models/Scratch_W6_S1.0_R1

entity_names:
        - Chemical 
        - Disease

# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_cased
#model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768

# positive label num (postive labels (3) + negative label (1))
#class_num: 4

# gpu
gpu: 0 


# training
train_epochs: 25 
train_batch_size:  4 
valid_batch_size:  4 
#test_batch_size: 4 


# training lr
train_lr: 1e-5
train_scheduler: linear
train_num_warmup_steps: 10 
max_patient_count: 5 


# restore model
restore_model: False
restore_model_path: experiments/bc5cdr/models/base/model_classification.pth
#restore_model_path: experiments/bc5cdr/models/{latest_path}/model_classification.pth

