# Configuration file for training model.

# data path
task_name: bc5cdr 

num_bio_labels:  3

finetune_dir: data/Mesh/PubMed/Immunology/finetune
corpus_dir: data/Mesh/PubMed/Immunology/conll
# model save dir
model_dir: models/immunology/{timestamp}


# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_cased
#model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768
hidden_size: 100

# gpu
gpu: -1 

max_patient_count: 3

# training
train_epochs: 20 
train_batch_size: 5 
valid_batch_size: 5 

# training lr
train_lr: 1e-5
train_scheduler: linear
train_num_warmup_steps: 10 

# restore model
restore_model: True
restore_model_path: models/immunology/base_models/model_spanDetection.pth

