# Configuration file for training model.

# data path
task_name: bc5cdr 


#gold_sample_ratio: 0.01
#random_seed: 1

gold_sample_ratio: 0.5 
random_seed: 1 

iteration: 5
cnt: 5

updated_documents: data/BC5CDR/finetune/updated_doc.json
unchanged_documents: data/BC5CDR/finetune/unchanged_doc.json

gold_annotation_dir: data/BC5CDR/gold
base_annotation_dir: data/BC5CDR/annotate
prev_annotation_dir: data/BC5CDR/annotate.It_W6_S0.5_R1_5_4
text_dir: data/BC5CDR/corpus

#conll_dir: data/BC5CDR/finetune/conll
#span_dir: data/BC5CDR/finetune/span
simulation_dir: data/BC5CDR/finetune/It_W6_S0.5_R1/5/5
conll_dir: data/BC5CDR/finetune/It_W6_S0.5_R1/5/5/conll
span_dir: data/BC5CDR/finetune/It_W6_S0.5_R1/5/5/span

entity_names:
        - Chemical 
        - Disease
    
label_weight_update: 6 
