# Configuration file for training model.

# data path
task_name: immunology 


finetune_dir: data/Mesh/PubMed/Immunology/finetune

document_root_dir: data/Mesh/PubMed/Immunology/span

# model save dir
model_dir: models/immunology/{timestamp}


# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_cased
#model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768

# positive label num (postive labels (3) + negative label (1))
#class_num: 4

#elastic_search: "localhost:9200"
elastic_search: "http://database:9200"
index_name: cancer_immunology_conf

# gpu
gpu: -1 


# training
train_epochs: 25 
train_batch_size:  4 
valid_batch_size:  4 
#test_batch_size: 4 


# training lr
train_lr: 1e-5
train_scheduler: linear
train_num_warmup_steps: 10 
max_patient_count: 3 


# restore model
restore_model: True
restore_model_path: models/immunology/base_models/model_spanClassification.pth

