# Configuration file for training model.

# data path
task_name: bc5cdr 

entities:
    - chemicals.dict
    - disease.dict

entity_names:
        - Chemical 
        - Disease

ent2int:
    chemicals: 0
    disease: 1
    others: 2

#word2vec: modules/autoner/PubMed-w2v.bin
word2vec: modules/autoner/BioWordVec_PubMed_MIMICIII_d200.vec.bin

corpus_dir: data/BC5CDR/conll

test_dir: data/BC5CDR/eval/test
output_dir: data/BC5CDR/eval/annotate.autoner


# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768
hidden_size: 100

# label num
class_num: 3

# gpu
gpu: 0 

# restore model
restore_model: True
restore_model_path: experiments/bc5cdr/autoner/models/model_best_autoner.pth
