# Configuration file for training model.

# data path
task_name: bc5cdr 

entities:
    - chemicals.dict
    - disease.dict

entity_names:
        - Chemical 
        - Disease

corpus_dir: data/BC5CDR/conll

test_dir: data/BC5CDR/eval/test
#output_dir: data/BC5CDR/eval/annotate.bond
output_dir: data/BC5CDR/eval/annotate.roster
#output_dir: data/BC5CDR/eval/annotate.bond3rd


# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_uncased

# nn model
dropout_rate: 0.3
embedding_dim: 768
hidden_size: 100

# label num
class_num: 5

# gpu
gpu: 0 

# restore model
restore_model: True
model_dir: experiments/bc5cdr/roster/models
#model_name: model_best_roster_ens.pth 
model_name: model_best_roster_0.pth 

