# Configuration file for training model.

# data path
task_name: bc5cdr 

#corpus_root_dir: data/BC5CDR/processed_corpus

corpus_dir: 
    - data/BC5CDR/eval/annotate.bond2nd
    - data/BC5CDR/eval/annotate.bond3rd
    #- data/BC5CDR/eval/annotate
    #- data/BC5CDR/eval/annotate.autoner
    #- data/BC5CDR/eval/annotate.bond
    #- data/BC5CDR/eval/annotate.supervised
    #- data/BC5CDR/eval/annotate.gold
