# Configuration file for training model.

# data path
task_name: ncbi 

num_bio_labels:  1

corpus_dir: data/NCBI/conll.bond

# model save dir
model_dir: experiments/ncbi/bond/models/2nd
#model_dir: experiments/bc5cdr/bond/models/3rd

# bert model
seed: 22

label2int:
    'O': 0
    'B-DISEASE': 1
    'I-DISEASE': 2

# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_uncased


# nn model
dropout_rate: 0.5
embedding_dim: 768
hidden_size: 100

# label num
class_num: 5

# gpu
gpu: 0 

# training
train_epochs: 100 
train_batch_size: 10 
valid_batch_size: 10 

# training lr
train_lr: 1e-4
train_scheduler: linear
train_num_warmup_steps: 10000 
max_patient_count: 5 

# restore model
restore_model: True
restore_model_path: experiments/ncbi/bond/models/model_best_bond.pth
#restore_model_path: experiments/bc5cdr/bond/models/2nd/model_best_bond.pth

