# Configuration file for training model.

# data path
task_name: ncbi 

entities:
    - disease.dict

entity_names:
        - Disease

corpus_dir: data/NCBI/conll

test_dir: data/NCBI/eval/test
output_dir: data/NCBI/eval/annotate.supervised


# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_uncased

# nn model
dropout_rate: 0.3
embedding_dim: 768
hidden_size: 100

# label num
class_num: 3

# gpu
gpu: 0 

# restore model
restore_model: True
model_dir: experiments/ncbi/supervised/models
model_name: model_best_supervised.pth 
