# Configuration file for training model.

# data path
task_name: bc5cdr 

text_dir: data/BC5CDR/eval/text

ann_dir: 
    - data/BC5CDR/eval/annotate.{path_name}
#    - data/BC5CDR/eval/annotate.autoner
#    - data/BC5CDR/eval/annotate.supervised
#    - data/BC5CDR/eval/annotate.debug
#    - data/BC5CDR/eval/annotate.roster
#    - data/BC5CDR/eval/annotate.bond2
