# Configuration file for training model.

# data path
task_name: bc5cdr 

num_bio_labels:  2

finetune_dir: data/BC5CDR/finetune/{path_name}
conll_dir: data/BC5CDR/finetune/{path_name}/conll

# model save dir
model_root_dir: experiments/bc5cdr/models
model_dir: experiments/bc5cdr/models/{path_name}


# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_cased
#model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768
hidden_size: 100

# gpu
gpu: 0 

max_patient_count: 3

# training
train_epochs: 20 
train_batch_size: 5 
valid_batch_size: 5 

# training lr
train_lr: 1e-5
train_scheduler: linear
train_num_warmup_steps: 10 

# restore model
restore_model: False
restore_model_path: experiments/bc5cdr/models/base/model_segmentation.pth
#restore_model_path: experiments/bc5cdr/models/{latest_path}/model_segmentation.pth

