# Configuration file for training model.

# data path
task_name: bc5cdr 


#gold_sample_ratio: 0.01
#random_seed: 1

gold_sample_ratio: {sample_ratio} 
random_seed: {random_seed} 

updated_documents: data/BC5CDR/finetune/updated_doc.json
unchanged_documents: data/BC5CDR/finetune/unchanged_doc.json

gold_annotation_dir: data/BC5CDR/gold
annotation_dir: data/BC5CDR/annotate
text_dir: data/BC5CDR/corpus

#conll_dir: data/BC5CDR/finetune/conll
#span_dir: data/BC5CDR/finetune/span
simulation_dir: data/BC5CDR/finetune/{path_name}
conll_dir: data/BC5CDR/finetune/{path_name}/conll
span_dir: data/BC5CDR/finetune/{path_name}/span

entity_names:
        - Chemical 
        - Disease
    
label_weight_update: {label_weight} 
