# Configuration file for training model.

# data path
task_name: bc5cdr 

cnt: {cnt}
iteration: {iteration}

#dict_dir: data/Mesh/dict
#processed_dict_dir: data/Mesh/processed_dict
#cytokine_dict_file: cytokine.dict
#tf_dict_file: tf.dict
#t-lymphocyte_dict_file: t-lymphocyte.dict 
#protein_dict_file: protein.dict 
                
#document_root_dir: data/BC5CDR/eval/text
document_root_dir: data/BC5CDR/corpus

#annotation_root_dir: data/BC5CDR/eval/annotate.{path_name}
annotation_root_dir: data/BC5CDR/annotate.{path_name}_{iteration}_{cnt}


corpus_dir: data/Corpus/BC5CDR

# model save dir
model_dir: experiments/bc5cdr/models

# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_cased
#model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768

# positive entities + unknown
#
processed_dict_dirs:
        - data/UMLS/processed_dict

dict_files: 
        - chemicals.dict
        - disease.dict


entity_names:
        - Chemical 
        - Disease
# gpu
gpu: 0 

# restore model
#restore_model_path: experiments/bc5cdr/models/{path_name}/model_classification.pth
restore_model_path: experiments/bc5cdr/models/{path_name}/{iteration}/{cnt}/model_classification.pth
segmentation_predict_config: configs/bc5cdr_segmentation_predict_iterate.yaml

normalize_entity: False
