# Configuration file for training model.

# data path
task_name: bc5cdr 
corpus_dir: data/Mesh
corpus_file: desc2023.xml

dict_dir: data/Mesh/dict
pubmed_pmid_dir: data/Mesh/PubMed/BC5CDR
pubmed_extract_dir: data/Mesh/PubMed/BC5CDR/extract


