# Configuration file for training model.

# data path
task_name: bc5cdr 

use_dictionary: True
dict_dir: 
    - data/Mesh/processed_dict
    - data/UMLS/processed_dict
#    - data/BC5CDR/processed_dict

#spacy_model: en_core_sci_sm
spacy_model: en_core_sci_lg
#spacy_model: en_ner_bc5cdr_md

dict_files:
    - chemicals.dict
    - disease.dict

entity2integer:
    chemicals: 0
    disease: 1


#corpus_dir: data/BC5CDR/corpus
#output_dir: data/BC5CDR/conll
corpus_dir: data/Mesh/PubMed/BC5CDR/extract
output_dir: data/Mesh/PubMed/BC5CDR/conll

use_pu_data: False
pu_data: data/Corpus/BC5CDR/df_pu_train.csv
