# Configuration file for training model.

# data path
task_name: bc5cdr 
corpus_dir: data/UMLS

dict_dir: data/UMLS/dict
processed_dict_dir: data/UMLS/processed_dict

entity_types:
    - disease 
    - chemicals

        

