# Configuration file for training model.

# data path
task_name: bc5cdr 

processed_dict_dir: data/BC5CDR/processed_dict

document_root_dir: data/BC5CDR/corpus
corpus_dir: data/Corpus/BC5CDR

# model save dir
model_dir: experiments/bc5cdr/models

# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_cased
# nn model
dropout_rate: 0.3
embedding_dim: 768

# positive label num
class_num: 2

# gpu
gpu: 0 

# training
train_epochs: 50
train_batch_size: 32 
valid_batch_size: 32 
test_batch_size: 8 


# training lr
train_lr: 1e-4
train_scheduler: linear
train_num_warmup_steps: 100 
max_patient_count: 3 


# restore model
restore_model: False
restore_model_path: experiments/bc5cdr/models/model_best_%suffix%.pth

