# Configuration file for training model.

# data path
task_name: bc5cdr 
umls_meta_files_dir: /home/aae14935wb/Share/UMLS/2023AA/META
#umls_meta_files_dir: /Users/kenyano/WORK/AIST/UMLS/META

entities:
#    - cytokine : C0079189
#    - transcription_factor : C0040648
#    - t_lymphocyte : C0039194
    disease:
        RI: C0012634
        Semantic: 
            - "Disease or Syndrome"
        UMLS_hops: 4

    chemicals:
        RI: C0220806
        Semantic:
            - "Chemical"
            - "Chemical Viewed Functionally"
            - "Chemical Viewed Structurally"
            - "Inorganic Chemical"
            - "Organic Chemical"
        UMLS_hops: 4

dict_dir: data/UMLS/dict

