# Configuration file for training model.

# data path
task_name: immunology 
corpus_dir: data/Mesh
corpus_file: desc2023.xml

dict_dir: data/Mesh/dict
processed_dict_dir: data/Mesh/processed_dict
cytokine_dict_file: cytokine.dict
tf_dict_file: tf.dict
t-lymphocyte_dict_file: t-lymphocyte.dict 
protein_dict_file: protein.dict 

document_root_dir: data/Mesh/pubmed/extract
corpus_dir: data/Corpus/Immunology


# model save dir
model_dir: experiments/Immunology/models

# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_cased
# nn model
dropout_rate: 0.3
embedding_dim: 768

# gpu
gpu: -1


# training
train_epochs: 50
train_batch_size: 32 
valid_batch_size: 32 
test_batch_size: 8 

# training lr
train_lr: 1e-4
train_scheduler: linear
train_num_warmup_steps: 100 
max_patient_count: 3 


# restore model
restore_model: False
restore_model_path: experiments/models/model_best.pth

