# Configuration file for training model.

# data path
task_name: immunology 

dict_dir: 
    - data/Mesh/processed_dict
    - data/UMLS/processed_dict

dict_files:
    - cytokine.dict
    - transcription_factor.dict
    - t_lymphocyte.dict

entity2integer:
    cytokine: 0
    transcription_factor: 1
    t_lymphocyte: 2

#spacy_model: en_core_sci_sm
spacy_model: en_core_sci_lg
#spacy_model: en_ner_bc5cdr_md

corpus_dir: data/Mesh/PubMed/Immunology/extract
output_dir: data/Mesh/PubMed/Immunology/conll

use_pu_data: True
pu_data: data/Corpus/Immunology/df_pu_train.csv
