# Configuration file for training model.

# data path
task_name: immunology 

use_dictionary: True
dict_dir: 
    - data/Mesh/processed_dict
    - data/UMLS/processed_dict

dict_files:
    - cytokine.dict
    - transcription_factor.dict
    - t_lymphocyte.dict

use_pu_train: False
pu_train_csv: experiments/immunology/models/train.csv

entity2integer:
    cytokine: 0
    transcription_factor: 1
    t_lymphocyte: 2

#spacy_model: en_core_sci_sm
#spacy_model: en_core_sci_lg
#spacy_model: en_ner_bc5cdr_md

corpus_dir: data/Mesh/PubMed/Immunology/extract
output_dir: data/Mesh/PubMed/Immunology/conll

