# Configuration file for training model.

# data path
task_name: immunology 
umls_meta_files_dir: /home/aae14935wb/Share/UMLS/2023AA/META
#umls_meta_files_dir: /Users/kenyano/WORK/AIST/UMLS/META


dict_dir: data/UMLS/dict

