# Configuration file for training model.

# data path
task_name: immunology 
corpus_dir: data/Mesh
corpus_file: desc2023.xml

dict_dir: data/Mesh/dict
processed_dict_dir: data/Mesh/processed_dict

entity_types:
    - cytokine
    - t_lymphocyte
    - transcription_factor

entity_dependency:
    cytokine:
        - t_lymphocyte
    transcription_factor:
        - t_lymphocyte
        

