# Configuration file for training model.

# data path
task_name: immunology 
umls_meta_files_dir: /home/aae14935wb/Share/UMLS/2023AA/META
#umls_meta_files_dir: /Users/kenyano/WORK/AIST/UMLS/META

entities:
    cytokine:
        RI: C0079189
        Semantic: 
            - "Amino Acid, Peptide, or Protein"
        UMLS_hops: 3

    transcription_factor:
        RI: C0040648
        Semantic: 
            - "Amino Acid, Peptide, or Protein"
        UMLS_hops: 3

    t_lymphocyte:
        RI: C0039194
        Semantic: 
            - "Cell"
        UMLS_hops: 3


dict_dir: data/UMLS/dict

