# Configuration file for training model.

# data path
task_name: immunology 
corpus_dir: data/Mesh
corpus_file: desc2023.xml

dict_dir: data/Mesh/dict
pubmed_pmid_dir: data/Mesh/PubMed/Immunology
#pubmed_pmid_file: pmid-cytokineTi-set.txt
pubmed_pmid_file: pmid.txt

pubmed_extract_dir: data/Mesh/PubMed/Immunology/extract

