# Configuration file for training model.

# data path
task_name: immunology 
umls_meta_files_dir: /home/aae14935wb/Share/UMLS/2023AA/META
#umls_meta_files_dir: /Users/kenyano/WORK/AIST/UMLS/META

entities:
    cytokine:
        RI: C0079189
        UMLS_hops: 1

    transcription_factor:
        RI: C0040648
        UMLS_hops: 1

    t_lymphocyte:
        RI: C0039194
        UMLS_hops: 1


dict_dir: data/UMLS/dict

