# Configuration file for training model.

# data path
task_name: immunology 
corpus_dir: data/Mesh
corpus_file: desc2023.xml

dict_dir: data/Mesh/dict
pubmed_pmid_dir: data/Mesh/pubmed
pubmed_extract_dir: data/Mesh/pubmed/extract
#corpus_bio_mapping_file: bio_mapping.pkl
#corpus_relation_mapping_file: relation_mapping.pkl
#corpus_event_mapping_file: event_mapping.pkl
#corpus_attribute_mapping_file: attribute_mapping.pkl




