# Configuration file for training model.

# data path
task_name: immunology 
corpus_file: desc2023.xml

dict_dir: data/UMLS/dict
processed_dict_dir: data/UMLS/processed_dict

document_root_dir: data/Mesh/PubMed/Immunology/extract
corpus_dir: data/Corpus/Immunology

# model save dir
model_dir: experiments/immunology/models

# PU threshold true negative percentile threshold
#pu_thres_pert: 2.5
pu_thres_pert: 0.5 

spy_ratio: 0.1


# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_cased
#model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.2
embedding_dim: 768

# positive label num
class_num: 3

# gpu
gpu: 0 

# training
train_epochs: 50
train_batch_size: 16 
valid_batch_size: 16 
test_batch_size: 8 


# training lr
train_lr: 1e-5
train_scheduler: linear
train_num_warmup_steps: 1000 
max_patient_count: 5 


# restore model
restore_model: False
restore_model_path: experiments/immunology/models/model_best_%suffix%.pth

