# Configuration file for training model.

# data path
task_name: jnlpba 
corpus_dir: data/Mesh
corpus_file: desc2023.xml

#dict_dir: data/Mesh/dict
#processed_dict_dir: data/Mesh/processed_dict
#cytokine_dict_file: cytokine.dict
#tf_dict_file: tf.dict
#t-lymphocyte_dict_file: t-lymphocyte.dict 
#protein_dict_file: protein.dict 

document_root_dir: data/Mesh/PubMed/JNLPBA/extract
annotation_root_dir: data/Mesh/PubMed/JNLPBA/annotate

corpus_dir: data/Corpus/JNLPBA

# model save dir
model_dir: experiments/jnlpba/models

# bert model
seed: 22
model_checkpoint: allenai/scibert_scivocab_cased
# nn model
dropout_rate: 0.3
embedding_dim: 768

# positive entities + unknown
#class_num: 6
entity_names:
        - protein 
        - cell_line
        - cell_type
        - DNA
        - RNA

# gpu
gpu: 0 

# restore model
restore_model_path: experiments/jnlpba/models/model_best.pth

