# Configuration file for training model.

# data path
task_name: ncbi 

#processed_dict_dir: data/BC5CDR/processed_dict

document_root_dir: data/NCBI/corpus
#document_root_dir: data/Mesh/PubMed/BC5CDR/extract

# model save dir
model_dir: experiments/ncbi/models

corpus_dir: data/Corpus/NCBI

# bert model
seed: 22
#model_checkpoint: allenai/scibert_scivocab_cased
model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768

# positive label num
class_num: 1

# PU threshold true negative percentile threshold
pu_thres_pert: 2.5 

spy_ratio: 0.1

# gpu
gpu: 0 

# training
train_epochs: 50
train_batch_size: 32 
valid_batch_size: 32 
test_batch_size: 8 


# training lr
train_lr: 1e-4
train_scheduler: linear
train_num_warmup_steps: 1000
max_patient_count: 3 


# restore model
restore_model: False
restore_model_path: experiments/ncbi/models/model_best_%suffix%.pth

