# Configuration file for training model.

# data path
task_name: ncbi 

# disease + others
#num_bio_labels:  2
#
# didease only (for debug)
num_bio_labels:  1

corpus_dir: data/NCBI/conll
#corpus_dir: data/Mesh/PubMed/BC5CDR/conll

# model save dir
model_dir: experiments/ncbi/segmentation/models

# bert model
seed: 22
#model_checkpoint: allenai/scibert_scivocab_cased
model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768
hidden_size: 100

# binary label for span [0,1]
class_num: 2

# gpu
gpu: 0 


# training
train_epochs: 50
train_batch_size: 8 
valid_batch_size: 8 

# training lr
train_lr: 1e-4
train_scheduler: linear
train_num_warmup_steps: 10000 
max_patient_count: 5 

# restore model
restore_model: False
restore_model_path: experiments/ncbi/segmentation/models/model_best_seg.pth

