# Configuration file for training model.

# data path
task_name: ncbi 

#dict_dir: data/Mesh/dict
#processed_dict_dir: data/Mesh/processed_dict
#cytokine_dict_file: cytokine.dict
#tf_dict_file: tf.dict
#t-lymphocyte_dict_file: t-lymphocyte.dict 
#protein_dict_file: protein.dict 
                
document_root_dir: data/NCBI/eval/test
annotation_root_dir: data/NCBI/eval/annotate.debug

corpus_dir: data/Corpus/NCBI

# model save dir
model_dir: experiments/ncbi/models

# bert model
seed: 22
#model_checkpoint: allenai/scibert_scivocab_cased
model_checkpoint: allenai/scibert_scivocab_uncased
# nn model
dropout_rate: 0.3
embedding_dim: 768

# positive entities + unknown

entity_names:
        - Disease
# gpu
gpu: 0 

# restore model
restore_model_path: experiments/ncbi/models/model_best_final.pth

segmentation_predict_config: configs/ncbi_segmentation_predict.yaml
