# Configuration file for training model.

# data path
task_name: ncbi 

#dict_dir: data/Mesh/dict
#processed_dict_dir: data/Mesh/processed_dict
#dict_dir: data/UMLS/dict
#processed_dict_dir: data/UMLS/processed_dict

spark: True


processed_dict_dirs:
        - data/NCBI/dict

dict_files: 
        - disease.dict

entity_names:
        - Disease

document_root_dir: data/NCBI/corpus
#document_root_dir: data/Mesh/PubMed/BC5CDR/extract
corpus_dir: data/Corpus/NCBI


segmentation_predict_config: configs/ncbi_segmentation_predict.yaml
